=== maiaimei/swift-demo/src/main/resources/META-INF/swift-mt-validation.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns="https://maiamy.cn/schema/swift"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://maiamy.cn/schema/swift"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="swift-mt-validation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="xsd:string"/>
                <xsd:element name="message-type" type="xsd:string"/>
                <xsd:element name="is-b2c" type="xsd:boolean"/>
                <xsd:element name="fields" type="fields"/>
                <xsd:element name="sequences" type="sequences" nillable="true" minOccurs="0"/>
                <xsd:element name="rules" type="rules" nillable="true" minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="sequences">
        <xsd:sequence>
            <xsd:element name="sequence" type="sequence" nillable="true" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="sequence">
        <xsd:sequence>
            <xsd:element name="fields" type="fields" nillable="true"/>
            <xsd:element name="rules" type="rules" nillable="true" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="name" use="required" type="xsd:string"/>
        <xsd:attribute name="status" use="required">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Sequence Status

    "M" indicates a field is mandatory;
    "O" indicates a field is optional.
                ]]></xsd:documentation>
            </xsd:annotation>
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="O"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="fields">
        <xsd:sequence>
            <xsd:element name="field" type="field" nillable="true" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="field">
        <xsd:sequence>
            <xsd:element name="components" type="components" nillable="true" minOccurs="0"/>
            <xsd:element name="fields" type="fields" nillable="true" minOccurs="0"/>
            <xsd:element name="rules" type="rules" nillable="true" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="no" use="required" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field No.
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="tag" use="required" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Tag
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="field-name" use="required" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Name
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="format" use="required" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Format
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="pattern" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Pattern
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="type" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Type
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="status" use="required">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Status

    "M" indicates a field is mandatory;
    "O" indicates a field is optional.
                ]]></xsd:documentation>
            </xsd:annotation>
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="O"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="options" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Field Options
    
    Multiple option split by "|"
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="components">
        <xsd:sequence>
            <xsd:element name="component" type="component" nillable="true" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="component">
        <xsd:attribute name="index" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Index
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="start-index" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Start Index
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="end-index" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component End Index
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="label" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Label
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="format" use="required" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Format
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="pattern" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Pattern
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="type" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Type
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="status" use="required">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Status

    "M" indicates a component is mandatory;
    "O" indicates a component is optional.
                ]]></xsd:documentation>
            </xsd:annotation>
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="O"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="options" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Component Options
    
    Multiple option split by "|"
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="rules">
        <xsd:sequence>
            <xsd:element name="rule" type="rule" nillable="true" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="rule">
        <xsd:attribute name="expression-string" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation><![CDATA[
    Spring Expression Language
                ]]></xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="bean-name" type="xsd:string"/>
        <xsd:attribute name="method-name" type="xsd:string"/>
        <xsd:attribute name="error-message" type="xsd:string"/>
    </xsd:complexType>

</xsd:schema>

=== maiaimei/swift-demo/src/main/resources/validation/mt7xx/MT784_761.xml
<?xml version="1.0" encoding="UTF-8"?>
<swift-mt-validation xmlns="https://maiamy.cn/schema/swift"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="https://maiamy.cn/schema/swift 
       https://maiamy.cn/schema/swift/swift-mt-validation.xsd">

    <id>mt784761ValidationConfig</id>
    <message-type>761</message-type>
    <b2c>false</b2c>
    <fields>
        <field no="2.1" tag="27A" field-name="Message Index/Total" format="1!n/1!n" status="M" />
        <field no="2.2" tag="21A" field-name="Customer Reference Number" format="16x" status="M" />
        <field no="2.3" tag="27" field-name="Sequence of Total" format="1!n/1!n" status="M" />
        <field no="2.4" tag="20" field-name="Undertaking Number" format="16x" status="M" />
        <field no="2.5" tag="52A" field-name="Issuer" format="[[/1!a][/34x]$]4!a2!a2!c[3!c]" status="O">
            <components>
                <component index="1" format="1!a" status="O"/>
                <component index="2" format="34x" status="O"/>
                <component index="3" format="4!a2!a2!c[3!c]" status="M"/>
            </components>
        </field>
        <field no="2.5" tag="52D" field-name="Issuer" format="[[/1!a][/34x]$]4*35x" status="O">
            <components>
                <component index="1" format="1!a" status="O"/>
                <component index="2" format="34x" status="O"/>
                <component index="3" format="35x" status="M"/>
                <component start-index="4" end-index="6" format="35x" status="O"/>
            </components>
        </field>
        <field no="2.6" tag="77U" field-name="Undertaking Terms and Conditions" format="150*65z" status="O" />
        <field no="2.7" tag="77L" field-name="Requested Local Undertaking Terms and Conditions" format="150*65z" status="O" />
    </fields>
    <rules>
        <rule expression-string="#block.getTagByName('52A') == null and #block.getTagByName('52D') == null"
              error-message="52A or 52D must be present" />
    </rules>

</swift-mt-validation>
